### PR TITLE
Bool private backup

### PR DESCRIPTION
**Pull request by nbroad1881**
turns out create_repo needs a boolean value, so I ~~use [Configparsers getboolean function.](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.getboolean)~~

Edit: cfg isn't actually a configparser object, so can just use the fastcore `get` function wrapped in `bool`

@jph00

### CODE REVIEW

**Comment by nbroad1881** [comment]
made some noob mistakes 😅

Sorry about that

**Comment by jph00** [comment]
Is it not working without this? I see in the source that it's using a `Config` object (https://fastcore.fast.ai/foundation.html#config) passing the bool type for that key already, so in theory it ought to be a bool already...

**Comment by nbroad1881** [comment]
I thought it would be bool too, but it comes out as int. Then create_repo throws an error.

image

**Comment by jph00** [comment]
I've asked @hamelsmu to take a look at the underlying cause - would rather fix that then do a workaround, so will leave this open for a bit if that's ok...

**Comment by hamelsmu** [comment]
<notes>

Ok so what is happening is that this is actually returning an int of `0` or `1`

which is fine, because this is what happens, I'm curious if there is a reason we need bool

```python
# These will pass
assert 0 == False
assert 1 == True
```

YUP it needs to be strictly boolean in the HF API LOL

image


</notes>

**Comment by hamelsmu** [comment]
@jph00 seems like you really want to return 0/1 instead of T/F so I wont' change fastcore ?

image

**Comment by hamelsmu** [comment]
So to me it seems reasonable that @nbroad1881 that he is casting this to bool

**Review by hamelsmu — COMMENTED** [review]
Made [this PR](https://github.com/fastai/fastcore/pull/623) to fastcore, but not entirely sure if we should make this change or not!  I am not sure if there are other implications that I don't know about.

We have a bunch of integration tests that all passed so I think its probably ok?  

Maybe @jph00 knows

**Comment by nbroad1881** [comment]
I could ask @Wauplin if he thinks the `huggingface_hub` library should handle any truthy value

**Comment by jph00** [comment]
I think my fastcore str2bool behavior is dumb. AFAICT it should return a
bool. Lemme try changing that and I'll see if it breaks anything. I'll
update here when either I've fixed fastcore or discovered it really does
need an int.

**Comment by Wauplin** [comment]
Values passed to `create_repo` are directly forwarded to the server where a parser validates the data. I don't think we ever want to accept implicit boolean casting server-side as this would highly depend on the language and framework we chose (which is not something the public can review easily). That's why `create_repo` is type annotated with `private: bool` and should be respected. Always better to let the client -here `fasthtml-hf`- decide how to deal with config values.

**Comment by jph00** [comment]
I've updated fastcore now and also updated the dep in the toml here. Hopefully that fixes it -- please create an issue if there's still a problem.

**Pull request closed without merging**
